version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/dockerConf/nginx/conf.d:/etc/nginx/conf.d
      - /docker/dockerConf/nginx/ssl:/etc/nginx/ssl
      - /docker/dockerConf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/:/app
    restart: always
    container_name: nginx_webserver
    networks:
      - stack_network
    environment:
      - TZ=Africa/Cairo 
networks:
  stack_network:
    external: true
